language: node_js
node_js:
- '0.11'
- '0.12'
- node
- iojs
env:
- TEST=cover
sudo: false
before_deploy:
- npm install -g npm
deploy:
  provider: npm
  email: info@openag.io
  api_key:
    secure: kND0SKq2hYMB2UpgsG+t7cCJPURIVQRxRJiPHlJk1k8qjT9ha6l4Npp98K67QI+l6JX5iHMngud8tHg+Vj/KqfRw6Ymf6FdXAnqc8lIU81vlUfXQYwZUdPl3Lkd7HtHLCedC3YivXQwVUKc9Uigas+czrssF6jRJddCCwu8JtMRXO1wJVNBAnOls+3sCFMiDqw8WJSD0yf1B2E0wZdNSPWQOUkPhhHBq23GNpwd28jQlcm2UgQe3F3fvPwwT2wCEoPowkTEe6Ukz5fpvuyxJTTJxvsvGFqKOAa7fpK89uuyRqYv2+3jzIIXEN6ygVLL+/ezhyVfQW4lRFKn5VrY3+teNmz4Ua6h0826+PN1Gs7UJuPvxcRrUnhnPyk/8JErceTgtvbnXsrchqtN+HD+9jM82G0E3tfZueE//Isq81fgGAo8usq30b+XEls4UUrZ3rWc4Ns6f0CL20vfFxHk00Y+6LPOZ1N5MMlYDoMwWAiNkh3cZTH6weRSL4gDWqjh3n4K7N4qV/kUvJ22+RmUu6fnLNfvGOnKb1Q08DAoakOqV3a14VcBeYZdOj0lKHN0x20T4f0wIlX5hVZZ8+HH3MSsCdmHKaVRBd9HHT8yHTEt13CmGmZgzek2Jh63FgeM+vwGNJWHUTmMrMi/kivu7v4KBJF+fQDpkIDYIdDZjT+k=
  on:
    node: node
    tags: true
    repo: OADA/valleyix-formats
before_install:
- npm install -g coveralls
script:
- npm run lint
- npm run style
- npm run $TEST
after_success:
- cat ./coverage/lcov.info | coveralls --verbose
